name: unit_test
services:
  mysql-8-0-36:
    image: mysql:8.0.44-debian
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - unit_test
  adminer:
    image: adminer:5.3.0-standalone
    container_name: adminer-standalone_2
    restart: unless-stopped
    ports:
      - "8090:8080"
    networks:
      - unit_test

networks:
  unit_test:
    name: unit_test
    external: true